version: '3'
services:
  zookeeper:
    image: kafka:latest
    volumes: 
      - ./zoo-data:/tmp/zookeeper
    ports:
      - 2181:2181
    networks: 
      - overlay
    command: /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties 

  kafka: 
    image: kafka:latest
    volumes: 
       - ./kafka-logs:/tmp/kafka-logs
    ports: 
       - 9092:9092
    networks:
       - overlay
    depends_on:
       - zookeeper
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override listeners=INTERNAL://kafka:9092 --override listener.security.protocol.map=INTERNAL:PLAINTEXT --override inter.broker.listener.name=INTERNAL

networks:
  overlay: 
     
