version: '3'
services:
  zookeeper:
    image: kafka:latest
    volumes:
      - zoo-data:/tmp/zookeeper
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2181:2181"
    networks:
      - overlay
    deploy:
      mode: global
      placement: 
        constraints: 
          - node.labels.zoo==1
    command: /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties

  kafka1:
    image: kafka:latest
    volumes:
       - kafka1-logs:/tmp/kafka-logs
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
       - "9094:9094"
    networks:
       - overlay
    depends_on:
       - zookeeper
    deploy: 
      mode: global
      placement: 
        constraints: 
          - node.labels.kafka==1
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override listeners=EXT://kafka1:9094,INT://kafka1:9093 --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT --override inter.broker.listener.name=INT --override advertised.listeners=EXT://node3:9094,INT://kafka1:9093 --override broker.id=1

  kafka2:
    image: kafka:latest
    volumes:
       - kafka2-logs:/tmp/kafka-logs
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
       - "9095:9095"
    networks:
       - overlay
    depends_on:
       - zookeeper
    deploy:
      mode: global  
      placement: 
        constraints: 
          - node.labels.kafka==2
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override listeners=EXT://kafka2:9095,INT://kafka2:9093 --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT --override inter.broker.listener.name=INT --override advertised.listeners=EXT://node4:9095,INT://kafka2:9093 --override broker.id=2


  kafka3:
    image: kafka:latest
    volumes:
       - kafka3-logs:/tmp/kafka-logs
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
       - "9096:9096"
    networks:
       - overlay
    depends_on:
       - zookeeper
    deploy:
      mode: global
      placement: 
        constraints: 
          - node.labels.kafka==3
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override listeners=EXT://kafka3:9096,INT://kafka3:9093 --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT --override inter.broker.listener.name=INT --override advertised.listeners=EXT://node5:9096,INT://kafka3:9093 --override broker.id=3

networks:
  overlay:

volumes:
  kafka1-logs:
  kafka2-logs:
  kafka3-logs:
  zoo-data:
