version: '3'
services:
  zookeeper:
    image: kafka:latest
    volumes:
      - zoo-service-data:/tmp/zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.zoo==1
    command: /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties

  kafka:
    image: kafka:latest
    volumes:
       - kafka-service-logs:/tmp/kafka-logs
    networks:
       - kafka-net
    deploy:
      mode: global
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zookeeper:2181 --override listeners=PLAINTEXT://:9092 --override listener.security.protocol.map=PLAINTEXT:PLAINTEXT --override inter.broker.listener.name=PLAINTEXT --override advertised.listeners=PLAINTEXT://:9092 --override broker.id=-1

  rest-proxy:
      image: confluentinc/cp-kafka-rest:4.1.0
      networks:
         - kafka-net
      ports:
         - 8082:8082
      deploy:
        replicas: 1
      environment:
         KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_REST_LISTENERS: http://0.0.0.0:8082
         KAFKA_REST_HOST_NAME: localhost

networks:
  kafka-net:

volumes:
  kafka-service-logs:
  zoo-service-data:
