version: '3'
services:
  zk1:
    image: kafka:latest
    volumes:
      - zoo-service-data:/tmp/zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==1
    command: /bin/bash -c "/kafka/startZookeeper.sh 1 zk1,zk2,zk3 && /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties"

  zk2:
    image: kafka:latest
    volumes:
      - zoo-service-data:/tmp/zookeeper
    ports:
      - 2182:2181
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==2
    command: /bin/bash -c "/kafka/startZookeeper.sh 2 zk1,zk2,zk3 && /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties"

  zk3:
    image: kafka:latest
    volumes:
      - zoo-service-data:/tmp/zookeeper
    ports:
      - 2183:2181
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==3
    command: /bin/bash -c "/kafka/startZookeeper.sh 3 zk1,zk2,zk3 && /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties"

  kafka:
    image: kafka:latest
    volumes:
       - kafka-service-logs:/tmp/kafka-logs
    networks:
       - kafka-net
    deploy:
      mode: global
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override zookeeper.connect=zk1:2181 --override listeners=PLAINTEXT://:9092 --override listener.security.protocol.map=PLAINTEXT:PLAINTEXT --override inter.broker.listener.name=PLAINTEXT --override advertised.listeners=PLAINTEXT://:9092 --override broker.id=-1

  rest-proxy:
      image: confluentinc/cp-kafka-rest:4.1.0
      networks:
         - kafka-net
      ports:
         - 8082:8082
      deploy:
        replicas: 1
      environment:
         KAFKA_REST_ZOOKEEPER_CONNECT: zk1:2181
         KAFKA_REST_LISTENERS: http://0.0.0.0:8082
         KAFKA_REST_HOST_NAME: localhost

networks:
  kafka-net:

volumes:
  kafka-service-logs:
  zoo-service-data:
